'use strict'

// --- Temporary debug instrumentation for tracking down the replay desync ---
// Every rng() call gets logged with which line called it and whether it
// happened during live play, recording, or replay. After reproducing the
// desync, call dumpRngLog() in the console (or click the on-screen link it
// creates) to download rng-log.json, do it for both the recording run and
// the replay of it, and diff them - the first index where "at" differs
// between the two files is the exact function causing the drift. Safe to
// strip out once the bug is found; adds no gameplay behavior.
const RNG_DEBUG = true
let rngLog = []

function rngDebugCaller() {
  const stack = (new Error()).stack || ''
  const lines = stack.split('\n').map(s => s.trim()).filter(Boolean)
  // rngDebugCaller -> rng -> randInt/chance/pick -> the real gameplay
  // consumer. Keep several frames instead of only the immediate helper.
  const frames = lines.slice(2, 10)
  const cleaned = frames.map(frame => frame.replace(/^at\s+/, ''))
  const direct = cleaned[0] || ''
  const semantic = cleaned.find(frame =>
    !/^(rng|randInt|chance|pick|rngDebugCaller)\b/.test(frame)
  ) || direct
  return {
    direct,
    semantic,
    stack: cleaned
  }
}

window.dumpRngLog = function () {
  const blob = new Blob([JSON.stringify(rngLog, null, 2)], {type: 'application/json'})
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  const ts = new Date().toISOString().replace(/[:.]/g, '-')
  a.href = url
  a.download = `rng-log-${ts}.json`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
  console.log(`Dumped ${rngLog.length} rng() calls.`)
}
window.clearRngLog = function () {
  rngLog = []
  console.log('rng log cleared.')
}
// Grabs just the entries around a given rng index (defaults to the range
// implied by window.lastReplayDiagnostic, padded by `pad` on each side)
// and copies them to the clipboard as JSON - avoids downloading/pasting
// a multi-MB file when you only need the handful of calls right around
// a desync point.
window.copyRngSlice = function (lo, hi, pad) {
  pad = pad === undefined ? 30 : pad
  if (lo === undefined || hi === undefined) {
    const d = window.lastReplayDiagnostic
    if (!d) {
      console.warn('No lastReplayDiagnostic available - pass lo/hi explicitly, e.g. copyRngSlice(1450, 1500).')
      return
    }
    // lastReplayDiagnostic's indices are positions in activeReplay.rng
    // (per-run, starts at 0 after character creation) - NOT the same
    // counter as rngLog.i, which counts every rng() call since page
    // load, including the ~thousands consumed by one-time world
    // generation before recording even starts. Filtering rngLog by
    // raw .i using the diagnostic's numbers silently grabs the wrong
    // era of the log. Filter by replayActionIndex instead, which is
    // self-consistent with the diagnostic's actionIndex.
    const slice = rngLog.filter(e =>
      e.mode === 'replay' && e.replayActionIndex !== null &&
      Math.abs(e.replayActionIndex - d.actionIndex) <= 1
    )
    const text = JSON.stringify(slice, null, 2)
    copy(text)
    console.log(`Copied ${slice.length} rng() calls around actionIndex ${d.actionIndex} to clipboard.`)
    return slice
  }
  const slice = rngLog.filter(e => e.i >= lo && e.i <= hi)
  const text = JSON.stringify(slice, null, 2)
  copy(text) // devtools console helper; falls back below if unavailable
  console.log(`Copied ${slice.length} rng() calls (i=${lo}..${hi}) to clipboard.`)
  return slice
}
// --- End temporary debug instrumentation ---

let replayRngCallers = []

/* ============================== REPLAY ==============================
       A replay is {version, initialState, actions, rng}. initialState is a
       normal buildSaveObject() snapshot taken the moment a run truly begins
       (right after character creation - the world itself is already
       generated by then, see init()/openRaceSelect()), so "reset to the
       beginning" is just loadGameFromObject() on that snapshot rather than
       re-simulating world generation. actions is every gameplay action
       accepted from that point on, in order. rng is every value rng() has
       produced since that point, in order - playback substitutes from this
       array instead of generating new randomness, so the exact same code
       path (movement/combat/loot/etc.) reproduces the exact same run. */
// v2 records non-turn NPC service interactions (e.g. opening the Herbalist)
// because they mutate talkFreezeTurns and therefore affect future RNG consumption.
const REPLAY_VERSION = 2
const REPLAY_ACTION_DELAY_MS = 12
// const REPLAY_ACTION_DELAY_MS = 169

let replayRecording = false // true once "Save replay" was chosen for the current character
let replayData = null       // {version, initialState, actions, rng} being recorded (or last loaded)

let replayPlaying = false   // true for the whole playback session; gates rng() substitution
let replayPaused = false    // true while paused; only affects whether the next action is scheduled
let activeReplay = null     // the replay object currently being played back
let replayActionIndex = 0
let replayRngIndex = 0
let replayTimer = null
// Replay simulation is deliberately independent of visual animation. When this
// is true, gameplay actions must finish synchronously so a background-tab throttle
// of requestAnimationFrame() cannot stall or reorder the deterministic simulation.
let replaySimulationMode = false
let replayAnimationsDisabled = false
let replayNextActionAt = 0
let replayActionRunning = false
// Per-action replay boundary diagnostics. Each entry captures the RNG cursor
// before/after the action, the recorded boundaries, and the exact calls made
// while that action was running. This is intentionally separate from rngLog,
// whose global index also includes RNG consumed before recording/replay.
let replayActionDiagnostics = []
let replayCurrentActionIndex = null
let replayNpcDiagnostics = []
// Always expose the latest diagnostic as a real global and on window.
// This makes it accessible from the browser console as either
// `lastReplayDiagnostic` or `window.lastReplayDiagnostic`.
var lastReplayDiagnostic = null
window.lastReplayDiagnostic = null
let preReplaySnapshot = null // whatever save was on screen before "Show Replay" rewound it

// Replay item identity is independent of array position. Inventory order can
// change after buying/selling/equipping, so recording only `idx` is fragile.
// IDs are assigned lazily to every gameplay item and persist in saves/replays.
let nextReplayItemId = 1

function ensureReplayItemIds() {
  // Replay playback must never lazily rewrite item identities. Older replays
  // contain IDs that were assigned only while recording, so assigning new IDs
  // during playback can steal/relabel an existing replay_item_N.
  if (replayPlaying) return
  const seen = new Set()
  const containers = [
    player?.inventory || [],
    merchantStock || [],
    groundItems || [],
    player?.equip ? Object.values(player.equip).filter(Boolean) : []
  ]
  for (const list of containers) for (const item of list) {
    if (!item || typeof item !== 'object') continue
    if (!item.replayId || seen.has(item.replayId)) item.replayId = `replay_item_${nextReplayItemId++}`
    seen.add(item.replayId)
    const m = String(item.replayId).match(/^replay_item_(\d+)$/)
    if (m) nextReplayItemId = Math.max(nextReplayItemId, Number(m[1]) + 1)
  }
}

function findReplayItemIndex(list, replayId, fallbackIdx) {
  ensureReplayItemIds()
  if (replayId) {
    const idx = list.findIndex(item => item?.replayId === replayId)
    if (idx >= 0) return idx
  }
  return Number.isInteger(fallbackIdx) ? fallbackIdx : -1
}

// Called at the exact point an action is accepted by the game - never from
// raw keydown, so held modifier keys and UI-only input are not recorded.
function recordReplayAction(action) {
  if (!replayRecording || replayPlaying) return
  ensureReplayItemIds()
  const previous = replayData.actions.at(-1)
  if (previous && previous._rngEnd === undefined) {
    previous._rngEnd = replayData.rng.length
    if (!Array.isArray(replayData._rngCallers)) replayData._rngCallers = []
    replayData._rngCallers[previous._recordedActionIndex] = replayRngCallers.slice()
  }
  replayRngCallers = []
  replayData.actions.push({
    ...action,
    _recordedActionIndex: replayData.actions.length,
    _rngStart: replayData.rng.length
  })
}

function startReplayRecording() {
  // replayRecording is still false here, so this snapshot has no nested
  // .replay field of its own.
  ensureReplayItemIds()
  const snapshot = buildSaveObject()
  // buildSaveObject contains live gameplay object references. Freeze the replay
  // starting state now; otherwise inventory/equipment/enemy objects mutate while
  // the recording continues and playback may start from a later-run state.
  const initialState = JSON.parse(JSON.stringify(snapshot))
  replayData = {version: REPLAY_VERSION, initialState, actions: [], rng: [], _rngCallers: []}
  replayRngCallers = []
  replayRecording = true
}

function updateReplayButton() {
  const btn = document.getElementById('btnReplay')
  if (!btn) return
  if (!replayData || !replayData.actions || !replayData.actions.length) {
    btn.style.display = 'none'
    return
  }
  btn.style.display = ''
  if (replayPlaying && replayPaused) btn.textContent = '▶ Resume Replay'
  else if (replayPlaying) btn.textContent = '⏸ Pause Replay'
  else btn.textContent = '▶ Show Replay'
}

function replayDesync(message) {
  log(message, 'bad')
  stopReplayPlayback()
}

function stopReplayPlayback() {
  if (replayTimer) {
    clearTimeout(replayTimer)
    replayTimer = null
  }
  replayPlaying = false
  replayPaused = false
  replaySimulationMode = false
  replayAnimationsDisabled = false
  replayNextActionAt = 0
  activeReplay = null
  replayActionIndex = 0
  replayRngIndex = 0
  replayCurrentActionIndex = null
  updateReplayButton()
}

function finishReplayPlayback() {
  const totalActions = activeReplay.actions.length
  const completedActions = replayActionIndex
  const remainingActions = activeReplay.actions.slice(completedActions)
  const diagnostic = {
    completedActions,
    totalActions,
    consumedRng: replayRngIndex,
    recordedRng: activeReplay.rng.length,
    remainingActions
  }
  console.warn('[Replay diagnostic]', diagnostic)
  diagnostic.actionBoundaries = replayActionDiagnostics.slice(-50)
  lastReplayDiagnostic = diagnostic
  window.lastReplayDiagnostic = diagnostic
  console.log('Replay diagnostic available as window.lastReplayDiagnostic', diagnostic)
  if (replayRngIndex !== activeReplay.rng.length) {
    log(`Replay finished, but consumed ${replayRngIndex} of ${activeReplay.rng.length} recorded RNG values - the current game version may have diverged from this run. Check the console for [Replay diagnostic].`, 'info')
  } else {
    log('Replay finished.', 'good')
  }
  stopReplayPlayback()
}

async function runReplayAction(action) {
  switch (action.type) {
    case 'move':
      await tryMove(action.dx, action.dy)
      break
    case 'inspect':
      inspect()
      break
    case 'forage':
      lootSkeletonOrForage()
      break
    case 'skipTurn':
      skipTurn()
      break
    case 'talk':
      if (action.npc === 'Old Hunter') interactOldHunter()
      break
    case 'openTrade': {
      const npc = npcs.find(n => n.name === action.npc)
      if (!npc) return replayDesync(`Replay desynchronized: could not find service NPC ${action.npc || ''}.`)
      // Mirror only the gameplay state changed by clicking the NPC. Do not
      // open the visual trade overlay during replay; UI timing must not affect
      // deterministic simulation.
      freezeNpcFromWandering(npc)
      serviceNpc = npc
      break
    }
    case 'buy': {
      let item = merchantStock.find(it => it?.replayId === action.replayId)
      if (!item && action.kind) item = merchantStock.find(it => it?.kind === action.kind && it?.name === action.name)
      if (!item && Number.isInteger(action.fallbackIndex)) item = merchantStock[action.fallbackIndex]
      if (!item) return replayDesync(`Replay desynchronized: could not find merchant item ${action.replayId || action.name || ''}.`)
      buyItem(item)
      break
    }
    case 'sell': {
      let idx = -1
      if (Number.isInteger(action.fallbackIndex) && player.inventory[action.fallbackIndex]) idx = action.fallbackIndex
      if (idx < 0) idx = findReplayItemIndex(player.inventory, action.replayId, -1)
      if (idx < 0 || !player.inventory[idx]) return replayDesync(`Replay desynchronized: could not find sold item ${action.replayId || action.name || ''}.`)
      sellItem(idx)
      break
    }
    case 'herbalist':
      if (action.action === 'purifyMushrooms') purifyMushrooms()
      else if (action.action === 'makePotion') makeHerbalistPotion()
      break
    case 'dig':
      tryDig({recordReplay: false})
      break
    case 'openCasket': {
      const idx = findReplayItemIndex(player.inventory, action.replayId, action.idx)
      if (idx < 0 || player.inventory[idx]?.kind !== 'treasurecasket') return replayDesync(`Replay desynchronized: could not find treasure casket ${action.replayId || ''}.`)
      openTreasureCasket()
      break
    }
    case 'blackKey': {
      const shouldEquip = !!action.equipped
      const isEquipped = !!player.equip.blackkey
      if (shouldEquip !== isEquipped) toggleBlackKey()
      break
    }
    case 'equip': {
      const idx = findReplayItemIndex(player.inventory, action.replayId, action.idx)
      if (idx < 0 || !player.inventory[idx]) return replayDesync(`Replay desynchronized: could not find equipped item ${action.replayId || ''}.`)
      equipItem(idx)
      break
    }
    case 'unequip':
      unequipItem(action.slot)
      break
    case 'useItem': {
      // Old replays contain both an inventory index and a lazily-assigned
      // replayId. Either can be stale after an earlier item-order divergence.
      // For identification, the only safe target is an artifact that is still
      // unidentified. Prefer the recorded slot when it has that property;
      // otherwise use the recorded id, then a deterministic fallback that does
      // not steal an artifact reserved by a later identification action.
      let idx = -1
      if (action.action === 'identifyArtifact') {
        if (Number.isInteger(action.idx)) {
          const indexedItem = player.inventory[action.idx]
          if (indexedItem?.kind === 'artifact' && !indexedItem.identified) idx = action.idx
        }
        if (idx < 0 && action.replayId) {
          const byId = player.inventory.findIndex(item => item?.replayId === action.replayId && item?.kind === 'artifact' && !item.identified)
          if (byId >= 0) idx = byId
        }
        if (idx < 0) {
          const laterIds = new Set(activeReplay.actions.slice(replayActionIndex).filter(a => a.type === 'useItem' && a.action === 'identifyArtifact' && a.replayId).map(a => a.replayId))
          idx = player.inventory.findIndex(item => item?.kind === 'artifact' && !item.identified && !laterIds.has(item.replayId))
        }
      } else {
        // For legacy recordings, the recorded slot is the compatibility anchor.
        // Use it first when it still contains a usable item; replay IDs are then
        // only a secondary lookup for newer recordings.
        if (Number.isInteger(action.idx) && player.inventory[action.idx]) {
          idx = action.idx
        } else {
          idx = findReplayItemIndex(player.inventory, action.replayId, -1)
        }
      }
      if (idx < 0 || !player.inventory[idx]) {
        const snapshot = player.inventory.map((item, i) => ({
          i, replayId: item?.replayId || null, kind: item?.kind || null,
          name: item?.name || null, identified: item?.identified ?? null,
          count: item?.count ?? null
        }))
        console.warn('[Replay item resolution failed]', {
          actionIndex: replayActionIndex - 1,
          action,
          inventory: snapshot
        })
        return replayDesync(`Replay desynchronized: could not find inventory item ${action.replayId || ''}.`)
      }
      const fn = {
        potion: usePotion,
        scroll: useScroll,
        homecomingscroll: useHomecomingScroll,
        speedpotion: useSpeedPotion,
        herb: useHerb,
        mushroom: useMushroom,
        ediblemushroom: useEdibleMushroom,
        berries: useBerries,
        tombstone: readTombstone,
        identifyArtifact
      }[action.action]
      if (!fn) return replayDesync(`Replay desynchronized: unknown item action ${action.action}.`)
      fn(idx)
      break
    }
    default:
      break
  }
}

function scheduleNextReplayAction(delayOverride) {
  if (!replayPlaying || replayPaused) return
  if (replayTimer) {
    clearTimeout(replayTimer)
    replayTimer = null
  }
  const delay = delayOverride === undefined
    ? Math.max(0, replayNextActionAt - performance.now())
    : Math.max(0, delayOverride)
  replayTimer = setTimeout(playNextReplayAction, delay)
}

async function playNextReplayAction() {
  replayTimer = null
  if (!replayPlaying || replayPaused || replayActionRunning) return
  replayActionRunning = true

  // A background tab may get its timer callback late. Catch up all actions whose
  // scheduled time has passed instead of treating the delayed callback as one
  // normal replay step. This preserves the replay's timeline across tab switches.
  let processed = 0
  const now = performance.now()
  while (replayPlaying && !replayPaused && replayActionIndex < activeReplay.actions.length &&
  (replayNextActionAt <= now || processed === 0)) {
    const actionIndex = replayActionIndex
    const action = activeReplay.actions[replayActionIndex++]
    replayCurrentActionIndex = actionIndex
    replayRngCallers = []
    const rngBefore = replayRngIndex

    // Replay is always simulation-first. Visual animations are disabled
    // whether the tab is active or backgrounded; no rAF-driven effect may
    // delay or alter the deterministic action/RNG sequence.
    replaySimulationMode = true
    replayAnimationsDisabled = true
    try {
      // IMPORTANT: await the action before checking RNG. Combat actions such as
      // tryMove() are async, so checking immediately would see only part of the
      // action (this caused the first-fight desync).
      await runReplayAction(action)
    } finally {
      replaySimulationMode = false
      replayAnimationsDisabled = false
    }

    const rngAfter = replayRngIndex
    const expectedStart = Number.isInteger(action._rngStart) ? action._rngStart : null
    const expectedEnd = expectedStart !== null
      ? (Number.isInteger(activeReplay.actions[actionIndex + 1]?._rngStart)
        ? activeReplay.actions[actionIndex + 1]._rngStart
        : activeReplay.rng.length)
      : null
    const expectedRng = expectedStart !== null ? (expectedEnd - expectedStart) : null
    const actualRng = rngAfter - rngBefore
    const boundaryDiagnostic = {
      actionIndex,
      userActionNumber: actionIndex + 1,
      type: action.type,
      action: JSON.parse(JSON.stringify(action)),
      cursorBefore: rngBefore,
      cursorAfter: rngAfter,
      actualRng,
      recordedRngStart: expectedStart,
      recordedRngEnd: expectedEnd,
      expectedRng,
      cursorOffset: expectedStart !== null ? (rngBefore - expectedStart) : null,
      rngIndexOffset: expectedStart !== null && replayRngCallers.length
        ? (replayRngCallers[0].rngIndex - expectedStart) : null,
      firstActualRngIndex: replayRngCallers.length ? replayRngCallers[0].rngIndex : null,
      lastActualRngIndex: replayRngCallers.length ? replayRngCallers.at(-1).rngIndex : null,
      actualRngCalls: replayRngCallers.map((e, n) => ({
        call: n + 1,
        replayRngIndex: e.rngIndex,
        value: e.value,
        semantic: e.semantic,
        direct: e.direct
      }))
    }
    replayActionDiagnostics.push(boundaryDiagnostic)
    if (replayActionDiagnostics.length > 200) replayActionDiagnostics.shift()
    console.debug('[Replay action boundary]', boundaryDiagnostic)
    if (!replayPlaying) {
      replayActionRunning = false
      return
    }
    if (expectedRng !== null && actualRng !== expectedRng) {
      const extraCalls = replayRngCallers.slice(expectedRng).map((e, n) => ({
        extraCall: n + 1,
        replayRngIndex: e.rngIndex,
        value: e.value,
        direct: e.direct,
        semantic: e.semantic,
        stack: e.stack
      }))
      const expectedCallers = (Array.isArray(activeReplay._rngCallers) && activeReplay._rngCallers[actionIndex]) || null
      lastReplayDiagnostic = {
        actionIndex, action, rngBefore, rngAfter, actualRng, expectedRng,
        actualRngCallers: replayRngCallers.slice(),
        extraRngCalls: extraCalls,
        actualRngSources: replayRngCallers.map((e, n) => ({
          call: n + 1,
          replayRngIndex: e.rngIndex,
          value: e.value,
          direct: e.direct,
          semantic: e.semantic,
          stack: e.stack
        })),
        // Group calls by the first non-RNG helper in the stack. This makes
        // the culprit obvious without manually reading every frame.
        npcDiagnostics: replayNpcDiagnostics.map(x => ({...x})),
        npcSummary: {
          total: npcs.length,
          nonStatic: npcs.filter(n => !n.static).length,
          static: npcs.filter(n => !!n.static).length,
          roster: npcs.map((n, i) => ({
            npcIndex: i, name: n.name, x: n.x, y: n.y,
            homeX: n.homeX, homeY: n.homeY, static: !!n.static, free: !!n.free
          }))
        },
        actualRngSourceSummary: replayRngCallers.reduce((m, e) => {
          const key = e.semantic || e.direct || '(unknown)'
          if (!m[key]) m[key] = {count: 0, rngIndices: [], values: []}
          m[key].count++
          m[key].rngIndices.push(e.rngIndex)
          m[key].values.push(e.value)
          return m
        }, {}),
        expectedRngCallers: expectedCallers,
        actionBoundaries: replayActionDiagnostics.slice(-20),
        totalRecordedRng: activeReplay.rng.length,
        previousAction: actionIndex > 0 ? activeReplay.actions[actionIndex - 1] : null,
        nextAction: activeReplay.actions[actionIndex + 1] || null,
        actualRngValues: replayRngCallers.map(x => x.value),
        message: 'First replay action with different RNG consumption'
      }
      window.lastReplayDiagnostic = lastReplayDiagnostic
      console.error('[Replay desync]', lastReplayDiagnostic)
      replayCurrentActionIndex = null
      replayDesync(`Replay desynchronized on action #${actionIndex + 1}: expected ${expectedRng} RNG value(s), but this action consumed ${actualRng}. Check window.lastReplayDiagnostic.`)
      replayActionRunning = false
      return
    }

    replayCurrentActionIndex = null
    replayNextActionAt += REPLAY_ACTION_DELAY_MS
    processed++

    // Prevent a pathological/corrupt replay from monopolising the main thread.
    // A normal background catch-up will finish on the next timer callback.
    if (processed >= 200) break
  }

  if (!replayPlaying || replayPaused) {
    replayActionRunning = false
    return
  }
  if (replayActionIndex >= activeReplay.actions.length) {
    replayActionRunning = false
    finishReplayPlayback()
    return
  }
  replayActionRunning = false
  scheduleNextReplayAction()
}

function startReplayPlayback() {
  replayActionDiagnostics = []
  replayCurrentActionIndex = null
  if (!replayData || !replayData.actions || !replayData.actions.length) return
  stopReplayPlayback()
  const replayToPlay = replayData
  // Requirement: preserve whatever was on screen before rewinding. Not
  // restorable through the UI in this first version, but kept in memory
  // rather than silently discarded.
  preReplaySnapshot = buildSaveObject()
  toggleInv(false)
  toggleMap(false)
  toggleTrade(false)
  toggleTreasureMap(false)
  clearAutoPath()
  pendingMove = null
  // loadGameFromObject() restores replayData/replayRecording from
  // data.replay - the snapshot has none, so it clears both; restore the
  // replay we're about to watch right after.
  loadGameFromObject(JSON.parse(JSON.stringify(replayToPlay.initialState)), {isReplayInit: true})
  replayData = replayToPlay
  replayRecording = false // watching freezes this replay; it is not extended by further play
  // These turn-driven counters aren't part of the save format at all
  // (a normal load doesn't reset them either), but the true value at the
  // moment a run starts is always zero/blank.
  turnCount = 0
  consecutiveWaitTurns = 0
  oldHunterQuestSerial = 0
  activeReplay = replayToPlay
  replayActionIndex = 0
  replayRngIndex = 0
  replayPlaying = true
  replayPaused = false
  replaySimulationMode = false
  // The first action keeps the existing visual delay, but subsequent actions are
  // tied to this monotonic timeline rather than to timer callback frequency.
  replayNextActionAt = performance.now() + REPLAY_ACTION_DELAY_MS
  updateReplayButton()
  log('Watching replay from the beginning...', 'info')
  scheduleNextReplayAction()
}

function pauseReplay() {
  if (!replayPlaying || replayPaused) return
  replayPaused = true
  if (replayTimer) {
    clearTimeout(replayTimer)
    replayTimer = null
  }
  updateReplayButton()
}

function resumeReplay() {
  if (!replayPlaying || !replayPaused) return
  replayPaused = false
  // Pausing freezes the replay timeline; resume from now with the normal delay.
  replayNextActionAt = performance.now() + REPLAY_ACTION_DELAY_MS
  updateReplayButton()
  scheduleNextReplayAction()
}

// If a hidden-tab timer was throttled, visibilitychange gives us an immediate
// chance to catch up as soon as the document becomes interactive again.
document.addEventListener('visibilitychange', () => {
  if (!document.hidden && replayPlaying && !replayPaused) {
    playNextReplayAction()
    render()
  }
})

function toggleReplayPlayback() {
  if (!replayPlaying) startReplayPlayback()
  else if (replayPaused) resumeReplay()
  else pauseReplay()
}

document.getElementById('btnReplay').addEventListener('click', toggleReplayPlayback)
